apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - name: priv
     image: quay.io/podman/stable
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
       runAsUser: 1724
